apiVersion: v2
appVersion: 4.7.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.0.4
description: Fedora Commons Repository 4
name: fcrepo
type: application
version: 2.0.2
